# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/gtx3g_bert_0_2/gtx3g_bert_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gtx3g_bert_0 || ORIG_REF_NAME==gtx3g_bert_0}]
