# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: f:/Programs/Verilog/FPGA_Group/test_gtx/gtx_ip/src/gtx3g_exdes_packaging.xdc

# IP: f:/Programs/Verilog/FPGA_Group/test_gtx/gtx_ip/src/rx_word_fifo/rx_word_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rx_word_fifo || ORIG_REF_NAME==rx_word_fifo}]

# IP: f:/Programs/Verilog/FPGA_Group/test_gtx/gtx_ip/src/gtx3g/gtx3g.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gtx3g || ORIG_REF_NAME==gtx3g}]

# XDC: f:/Programs/Verilog/FPGA_Group/test_gtx/gtx_ip/src/rx_word_fifo/rx_word_fifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rx_word_fifo || ORIG_REF_NAME==rx_word_fifo}] {/U0 }]/U0 ]]

# XDC: f:/Programs/Verilog/FPGA_Group/test_gtx/gtx_ip/src/gtx3g/gtx3g.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gtx3g || ORIG_REF_NAME==gtx3g}] {/inst }]/inst ]]

# XDC: f:/Programs/Verilog/FPGA_Group/test_gtx/gtx_ip/src/gtx3g/gtx3g_ooc.xdc
