# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/example_design/gtx3g_exdes.xdc

# IP: ip/gtx3g/gtx3g.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gtx3g || ORIG_REF_NAME==gtx3g}]
