# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/ljzhu/test_gtx/gtx3g_ex/gtx3g_ex.tmp/gtx3g_bert_axi_v1_0_project/gtx3g_bert_axi_v1_0_project.srcs/sources_1/ip/async_dual_port_bram/async_dual_port_bram.xci
# IP: The module: 'async_dual_port_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/ljzhu/test_gtx/gtx3g_ex/gtx3g_ex.tmp/gtx3g_bert_axi_v1_0_project/gtx3g_bert_axi_v1_0_project.srcs/sources_1/ip/async_dual_port_bram/async_dual_port_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_dual_port_bram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: e:/ljzhu/test_gtx/gtx3g_ex/gtx3g_ex.tmp/gtx3g_bert_axi_v1_0_project/gtx3g_bert_axi_v1_0_project.srcs/sources_1/ip/async_dual_port_bram/async_dual_port_bram.xci
# IP: The module: 'async_dual_port_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/ljzhu/test_gtx/gtx3g_ex/gtx3g_ex.tmp/gtx3g_bert_axi_v1_0_project/gtx3g_bert_axi_v1_0_project.srcs/sources_1/ip/async_dual_port_bram/async_dual_port_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_dual_port_bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
