# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/Programs/Verilog/FPGA_Group/test_gtx/gtx3g_ex/gtx3g_ex.tmp/gtx3g_bert_axi_v1_0_project/gtx3g_bert_axi_v1_0_project.srcs/sources_1/ip/gtx3g_bert_0_1/gtx3g_bert_0.xci
# IP: The module: 'gtx3g_bert_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: f:/Programs/Verilog/FPGA_Group/test_gtx/gtx3g_ex/gtx3g_ex.tmp/gtx3g_bert_axi_v1_0_project/gtx3g_bert_axi_v1_0_project.srcs/sources_1/ip/gtx3g_bert_0_1/src/rx_word_fifo/rx_word_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rx_word_fifo || ORIG_REF_NAME==rx_word_fifo}]

# IP: f:/Programs/Verilog/FPGA_Group/test_gtx/gtx3g_ex/gtx3g_ex.tmp/gtx3g_bert_axi_v1_0_project/gtx3g_bert_axi_v1_0_project.srcs/sources_1/ip/gtx3g_bert_0_1/src/gtx3g/gtx3g.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gtx3g || ORIG_REF_NAME==gtx3g}]

# XDC: f:/Programs/Verilog/FPGA_Group/test_gtx/gtx3g_ex/gtx3g_ex.tmp/gtx3g_bert_axi_v1_0_project/gtx3g_bert_axi_v1_0_project.srcs/sources_1/ip/gtx3g_bert_0_1/src/rx_word_fifo/rx_word_fifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rx_word_fifo || ORIG_REF_NAME==rx_word_fifo}] {/U0 }]/U0 ]]

# XDC: f:/Programs/Verilog/FPGA_Group/test_gtx/gtx3g_ex/gtx3g_ex.tmp/gtx3g_bert_axi_v1_0_project/gtx3g_bert_axi_v1_0_project.srcs/sources_1/ip/gtx3g_bert_0_1/src/gtx3g/gtx3g.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gtx3g || ORIG_REF_NAME==gtx3g}] {/inst }]/inst ]]

# XDC: f:/Programs/Verilog/FPGA_Group/test_gtx/gtx3g_ex/gtx3g_ex.tmp/gtx3g_bert_axi_v1_0_project/gtx3g_bert_axi_v1_0_project.srcs/sources_1/ip/gtx3g_bert_0_1/src/gtx3g/gtx3g_ooc.xdc

# XDC: f:/Programs/Verilog/FPGA_Group/test_gtx/gtx3g_ex/gtx3g_ex.tmp/gtx3g_bert_axi_v1_0_project/gtx3g_bert_axi_v1_0_project.srcs/sources_1/ip/gtx3g_bert_0_1/src/gtx3g_exdes_packaging.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtx3g_bert_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: F:/Programs/Verilog/FPGA_Group/test_gtx/gtx3g_ex/gtx3g_ex.tmp/gtx3g_bert_axi_v1_0_project/gtx3g_bert_axi_v1_0_project.srcs/sources_1/ip/gtx3g_bert_0_1/gtx3g_bert_0.xci
# IP: The module: 'gtx3g_bert_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: f:/Programs/Verilog/FPGA_Group/test_gtx/gtx3g_ex/gtx3g_ex.tmp/gtx3g_bert_axi_v1_0_project/gtx3g_bert_axi_v1_0_project.srcs/sources_1/ip/gtx3g_bert_0_1/src/rx_word_fifo/rx_word_fifo.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rx_word_fifo || ORIG_REF_NAME==rx_word_fifo}]

# IP: f:/Programs/Verilog/FPGA_Group/test_gtx/gtx3g_ex/gtx3g_ex.tmp/gtx3g_bert_axi_v1_0_project/gtx3g_bert_axi_v1_0_project.srcs/sources_1/ip/gtx3g_bert_0_1/src/gtx3g/gtx3g.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gtx3g || ORIG_REF_NAME==gtx3g}]

# XDC: f:/Programs/Verilog/FPGA_Group/test_gtx/gtx3g_ex/gtx3g_ex.tmp/gtx3g_bert_axi_v1_0_project/gtx3g_bert_axi_v1_0_project.srcs/sources_1/ip/gtx3g_bert_0_1/src/rx_word_fifo/rx_word_fifo.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rx_word_fifo || ORIG_REF_NAME==rx_word_fifo}] {/U0 }]/U0 ]]

# XDC: f:/Programs/Verilog/FPGA_Group/test_gtx/gtx3g_ex/gtx3g_ex.tmp/gtx3g_bert_axi_v1_0_project/gtx3g_bert_axi_v1_0_project.srcs/sources_1/ip/gtx3g_bert_0_1/src/gtx3g/gtx3g.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gtx3g || ORIG_REF_NAME==gtx3g}] {/inst }]/inst ]]

# XDC: f:/Programs/Verilog/FPGA_Group/test_gtx/gtx3g_ex/gtx3g_ex.tmp/gtx3g_bert_axi_v1_0_project/gtx3g_bert_axi_v1_0_project.srcs/sources_1/ip/gtx3g_bert_0_1/src/gtx3g/gtx3g_ooc.xdc

# XDC: f:/Programs/Verilog/FPGA_Group/test_gtx/gtx3g_ex/gtx3g_ex.tmp/gtx3g_bert_axi_v1_0_project/gtx3g_bert_axi_v1_0_project.srcs/sources_1/ip/gtx3g_bert_0_1/src/gtx3g_exdes_packaging.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtx3g_bert_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
