set_property SRC_FILE_INFO {cfile:f:/Programs/Verilog/FPGA_Group/test_gtx/gtx3g_ex/gtx3g_ex.tmp/gtx3g_bert_axi_v1_0_project/gtx3g_bert_axi_v1_0_project.srcs/sources_1/ip/gtx3g_bert_0_1/src/gtx3g_exdes_packaging.xdc rfile:../../../gtx3g_bert_axi_v1_0_project.srcs/sources_1/ip/gtx3g_bert_0_1/src/gtx3g_exdes_packaging.xdc id:1 order:EARLY scoped_inst:inst} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X0Y5 [get_cells gtx3g_support_i/gtx3g_init_i/inst/gtx3g_i/gt0_gtx3g_i/gtxe2_i]
set_property src_info {type:SCOPED_XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X0Y6 [get_cells gtx3g_support_i/gtx3g_init_i/inst/gtx3g_i/gt1_gtx3g_i/gtxe2_i]
